<?php

namespace App\Listeners;

use App\AgentSquad\Assistants\TextAssistant;
use App\Events\GenerateAiRemediation;
use App\Models\Alert;
use App\Models\Asset;
use App\Models\Port;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class GenerateAiRemediationListener extends AbstractListener
{
    private const string NO_SCRIPT_TOKEN = '<NO_SCRIPT>';

    public function viaQueue(): string
    {
        return self::LOW;
    }

    protected function handle2($event)
    {
        if (!($event instanceof GenerateAiRemediation)) {
            throw new \Exception('Invalid event type!');
        }

        $scan = $event->scan();
        $port = $event->port();
        $alert = $event->alert();

        if (!$scan || !$port || !$alert) {
            throw new \Exception("Invalid event! (scan={$event->scanId}, port={$event->portId}, alert={$event->alertId})");
        }

        Log::debug("Generating AI remediation for scan: ({$scan->ports_scan_id}, {$scan->vulns_scan_id}), alert: {$alert->title}");
        $start = microtime(true);

        $aiRemediation = $this->generateAiRemediation($port, $alert);

        $stop = microtime(true);
        Log::debug("AI remediation generated for scan: ({$scan->ports_scan_id}, {$scan->vulns_scan_id}), alert: {$alert->title}, time: " . ((int)ceil($stop - $start)) . " seconds");
        Log::debug("Updating alert for scan: ({$scan->ports_scan_id}, {$scan->vulns_scan_id}), alert: {$alert->title}");
        $start = microtime(true);

        $alert->ai_remediation = $aiRemediation['content'];
        $alert->false_positive = $aiRemediation['is_false_positive'];
        $alert->save();

        $stop = microtime(true);
        Log::debug("Alert updated for scan: ({$scan->ports_scan_id}, {$scan->vulns_scan_id}), alert: {$alert->title}, time: " . ((int)ceil($stop - $start)) . " seconds");
    }

    private function generateAiRemediation(Port $port, Alert $alert, string $mode = 'both'): array
    {
        $category = $this->detectVulnerabilityCategory($alert);
        $context = $this->gatherSecurityContext($port, $alert, $category);
        $results = [];
        $isFalsePositive = false;

        if ($mode === 'explanation' || $mode === 'both') {
            $results['explanation'] = $this->processLlmPart($port, $alert, $category, $context, 'explanation', null, $isFalsePositive);
        }
        if (!$isFalsePositive) {
            $isFalsePositive = $this->isFalsePositiveExplanation($results['explanation'] ?? '');
        }
        if ($mode === 'script' || $mode === 'both') {
            if ($isFalsePositive) {
                $results['script'] = self::NO_SCRIPT_TOKEN;
            } else {
                $results['script'] = $this->processLlmPart($port, $alert, $category, $context, 'script', $results['explanation'] ?? null);
            }
        }

        $aiRemediation = $results['explanation'] ?? '';

        if (empty(trim($aiRemediation)) && ($mode === 'explanation' || $mode === 'both')) {
            $aiRemediation = "### " . __('Analyse de la vulnérabilité') . "\n\n" .
                __('Désolé, l\'explication détaillée n\'a pas pu être générée pour cette alerte.') . "\n\n" .
                "**" . __('Détails détectés :') . "**\n" .
                "- **" . __('Vulnérabilité :') . "** " . ($alert->vulnerability ?? 'N/A') . "\n" .
                "- **" . __('Solution recommandée :') . "** " . ($alert->remediation ?? 'N/A');
        }

        $scriptResult = trim($results['script'] ?? '');

        if ($this->shouldDisplayScript($scriptResult)) {
            $aiRemediation .= "\n\n---\n\n### " . __('Script de Remédiation (BASH)') . "\n\n";
            $aiRemediation .= "> " . __('This script is automatically generated by AI. Please review it carefully before running.') . "\n\n";
            $aiRemediation .= "```bash\n" . $scriptResult . "\n```";
        }
        return [
            'content' => $aiRemediation,
            'is_false_positive' => $isFalsePositive,
        ];
    }

    private function shouldDisplayScript(string $script): bool
    {
        if ($script === '') {
            return false;
        }
        return !Str::contains(Str::lower($script), Str::lower(self::NO_SCRIPT_TOKEN));
    }

    private function isFalsePositiveExplanation(string $explanation): bool
    {
        $normalized = Str::lower($explanation);
        return Str::contains($normalized, '<is_false_positive>true</is_false_positive>')
            || (preg_match('/^\s*true\s*(?:\r?\n|$)/i', $explanation) === 1 && Str::contains($normalized, 'faux positif'));
    }

    private function sanitizeFalsePositiveExplanation(string $explanation): string
    {
        $clean = preg_replace('/<is_false_positive>\s*true\s*<\/is_false_positive>/i', '', $explanation);
        $clean = preg_replace('/^\s*true\s*(\r?\n)+/i', '', $clean ?? '');
        return trim($clean ?? '');
    }

    private function detectVulnerabilityCategory(Alert $alert): string
    {
        $type = Str::lower($alert->type ?? '');
        if (Str::contains($type, ['quickhits_file', 'config_file', 'backup_file', 'file_alert', 'file_v3'])) {
            return 'file_exposed';
        }
        if (Str::contains($type, ['weak_cipher', 'ssl_certificate', 'tls_', 'cipher'])) {
            return "weak_cipher";
        }
        if (!empty($alert->cve_id)) {
            return "cve";
        }
        return "general";
    }

    private function gatherSecurityContext(Port $port, Alert $alert, string $category): array
    {
        /** @var Asset $asset */
        $asset = $port->scan->asset;
        $assetTags = $asset->tags->pluck('tag')->toArray();
        $portTags = $port->tags->pluck('tag')->toArray();
        $tags = array_unique(array_merge($assetTags, $portTags));
        $technology = 'unknown';

        if (!empty($port->service) && $port->service !== 'unknown') {
            $technology = $port->service;
        }
        if (!empty($port->product) && $port->product !== 'unknown') {
            $technology = $port->product;
        }

        $context = [
            'ip' => $port->ip ?? 'N/A',
            'port' => $port->port ?? 0,
            'protocol' => $port->protocol ?? 'tcp',
            'vulnerability' => $alert->vulnerability ?? '',
            'title' => $alert->title ?? '',
            'technology' => $technology,
            'cve_id' => $alert->cve_id ?? null,
            'tags' => implode(', ', $tags),
        ];

        if ($category === 'file_exposed') {
            $url = $this->extractExposedUrl($alert, $port);
            if ($url) {
                $context['exposed_url'] = $url;
                $this->fetchExposedContent($url, $context);
            }
        }
        if ($context['technology'] === 'unknown' && in_array($category, ['file_exposed', 'weak_cipher', 'general'])) {
            $context['technology'] = $this->probeTechnology($context['ip'], (int)$context['port']);
        }
        if ($category === 'cve' && $context['cve_id']) {
            $context['cve_info'] = "NIST NVD: https://nvd.nist.gov/vuln/detail/" . strtoupper($context['cve_id']);
        }
        return $context;
    }

    private function extractExposedUrl(Alert $alert, Port $port): ?string
    {
        $url = null;
        $searchIn = ($alert->vulnerability ?? '') . ' ' . ($alert->title ?? '');

        if (!$url && preg_match('/(?:url|cible|target|host|matched|exposé)\s*:\s*(?:https?:\/\/)?([^\s<>"\']+)/i', $searchIn, $matches)) {
            $url = $matches[1];
        }

        $hasPath = false;

        if ($url) {
            $parsed = parse_url(Str::contains($url, '://') ? $url : 'http://' . $url);
            $hasPath = !empty($parsed['path']) && $parsed['path'] !== '/';
        }
        if (!$hasPath) {
            if (preg_match('/(?:fichier|file|path|chemin|filename)\s*:\s*([^\s<>"\']+)/i', $searchIn, $matches)) {
                $path = ltrim($matches[1], '/');
                $base = $url ?: ($port->ip . ($port->port != 80 && $port->port != 443 ? ':' . $port->port : ''));
                $url = rtrim($base, '/') . '/' . $path;
            }
        }
        if ($url) {
            $url = Str::trim($url);
            if (!Str::contains($url, '://')) {
                $scheme = ($port->ssl || $port->port === 443) ? 'https://' : 'http://';
                $url = $scheme . ltrim($url, '/');
            }
            return $url;
        }
        return null;
    }

    private function fetchExposedContent(string $url, array &$context): void
    {
        try {
            $response = Http::withOptions(['verify' => false])->timeout(10)->get($url);
            if ($response->successful()) {

                $context['file_content'] = Str::limit($response->body(), 4000);
                $serverHeader = Str::lower($response->header('Server', ''));
                $poweredBy = Str::lower($response->header('X-Powered-By', ''));

                if (Str::contains($serverHeader, 'nginx')) {
                    $context['technology'] = 'nginx';
                } elseif (Str::contains($serverHeader, 'apache') || Str::contains($poweredBy, 'apache')) {
                    $context['technology'] = 'apache';
                }
            } else {
                Log::warning("Fetch failed ($url): " . $response->status());
            }
        } catch (\Exception $e) {
            Log::warning("Fetch failed ($url): " . $e->getMessage());
        }
    }

    private function probeTechnology(string $ip, int $port): string
    {
        try {
            foreach (["https://$ip:$port", "http://$ip:$port"] as $url) {

                $response = Http::withOptions(['verify' => false])->timeout(3)->head($url);
                $server = strtolower($response->header('Server', ''));

                if (Str::contains($server, 'nginx')) {
                    return 'nginx';
                }
                if (Str::contains($server, 'apache')) {
                    return 'apache';
                }
            }
        } catch (\Exception $e) {
            Log::warning($e->getMessage());
        }
        return 'unknown';
    }

    private function processLlmPart(Port $port, Alert $alert, string $category, array $context, string $type, ?string $explanation = null, ?bool &$detectedFalsePositive = null): string
    {
        $title = $alert->title ?? '';
        $alertType = $alert->type ?? '';
        $fileContent = $context['file_content'] ?? '';

        if ($category === 'file_exposed' && !empty($fileContent) && $type === 'explanation') {

            $fpResult = TextAssistant::use()
                ->withPrompt('false_positive_prompt', array_merge($context, [
                    'content' => $fileContent,
                    'title' => $title,
                    'type' => $alertType,
                ]))
                ->text();

            if (Str::contains(Str::lower($fpResult), '<is_false_positive>true</is_false_positive>')) {
                $detectedFalsePositive = true;
                return $this->sanitizeFalsePositiveExplanation($fpResult);
            }
        }

        $template = $this->resolveTemplate($category, $type);
        $vars = array_merge($context, [
            'content' => $fileContent,
            'title' => $title,
            'type' => $alertType,
            'remediation' => $alert->remediation ?? '',
            'technology_upper' => Str::upper($context['technology']),
            'domain' => $context['ip'],
            'filename' => basename(parse_url($context['exposed_url'] ?? '', PHP_URL_PATH) ?: 'file'),
            'analysis_context' => $explanation ?? '',
            'risky_parts' => !empty($fileContent) ? $fileContent : 'Analyse en cours...',
        ]);

        if ($type === 'script') {

            $scriptDir = base_path("database/seeders/remediations");
            $scriptFile = match ($category) {
                'file_exposed' => "script_{$context['technology']}.bash",
                'weak_cipher' => "fix_weak_ciphers_{$context['technology']}.bash",
                default => null
            };

            if ($scriptFile) {
                if (file_exists("$scriptDir/$scriptFile")) {
                    $vars['script_content'] = file_get_contents("$scriptDir/$scriptFile");
                } else {
                    Log::warning("Script template not found: {$scriptFile}. Returning NO_SCRIPT token.");
                    return self::NO_SCRIPT_TOKEN;
                }
            }
        }

        $timeout = ($type === 'explanation') ? 120 : 60;
        $response = TextAssistant::use()
            ->withTimeout($timeout)
            ->withPrompt($template, $vars)
            ->text();

        if ($type === 'explanation' && $this->isFalsePositiveExplanation($response)) {
            $detectedFalsePositive = true;
            $response = $this->sanitizeFalsePositiveExplanation($response);
        }
        if ($type === 'script' && Str::contains(Str::lower(trim($response)), Str::lower(self::NO_SCRIPT_TOKEN))) {
            return self::NO_SCRIPT_TOKEN;
        }
        return $response;
    }

    private function resolveTemplate(string $category, string $type): string
    {
        $map = [
            'file_exposed' => [
                'explanation' => 'file_removal_explanation_only_prompt',
                'script' => 'file_removal_script_only_prompt',
            ],
            'weak_cipher' => [
                'explanation' => 'weak_cipher_explanation_prompt',
                'script' => 'weak_cipher_script_only_prompt',
            ],
            'cve' => [
                'explanation' => 'cve_explanation_prompt',
                'script' => 'general_script_only_prompt',
            ],
            'general' => [
                'explanation' => 'general_prompt',
                'script' => 'general_script_only_prompt',
            ]
        ];
        return $map[$category][$type] ?? 'explanation_only_prompt';
    }
}
