<?php

use App\Http\Controllers\Iframes\FrameworksController;
use App\Http\Middleware\CheckPermissionsHttpRequest;
use App\Http\Middleware\LogHttpRequests;
use Illuminate\Http\Request;
use function Laravel\Folio\{middleware, name, render};

middleware([LogHttpRequests::class, 'auth', CheckPermissionsHttpRequest::class]);
name('frameworks');
render(function (Request $request) {
  return app(FrameworksController::class)($request);
});
?>

<x-layouts.app>

  @push('styles')
  <style>

    /* Nested lists generated by YnhFramework::html() */
    .ul-small-padding {
      padding-left: 1rem;
    }

  </style>
  @endpush

  <div class="ui:mx-auto ui:flex ui:w-full ui:max-w-7xl ui:flex-col ui:gap-6 ui:px-4 ui:py-8 ui:lg:px-8">

    <x-ui.page-header :title="__('Frameworks')"
                      :subtitle="__('Security frameworks and standards. Load one to make it available to CyberBuddy.')"/>

    {{-- Full-text search in the frameworks content (server side) --}}
    <form method="get" action="{{ route('frameworks') }}"
          class="ui:m-0 ui:flex ui:flex-wrap ui:items-end ui:gap-3 ui:rounded-xl ui:border ui:border-solid ui:border-line ui:bg-surface ui:p-4 ui:shadow-xs">
      <x-ui.input id="search" name="search" value="{{ $search }}" class="ui:flex-1"
                  :placeholder="__('Enter one or more keywords...')" :aria-label="__('Search')"/>
      <x-ui.button type="submit" icon="magnifying-glass">{{ __('Search') }}</x-ui.button>
      @if($search)
        <x-ui.button variant="ghost" :href="route('frameworks')">{{ __('Reset') }}</x-ui.button>
      @endif
    </form>

    @if($highlights->isNotEmpty())

      {{-- Search results: matching blocks per framework, words in bold --}}
      @foreach($highlights as $highlight)
        <x-ui.card :title="\Illuminate\Support\Str::upper($highlight->framework->name)"
                   :subtitle="\Illuminate\Support\Str::lower($highlight->framework->provider)">
          <div class="ui:flex ui:flex-col ui:gap-3">
            @foreach($highlight->highlights as $h)
              <pre class="ui:m-0 ui:whitespace-pre-wrap ui:break-words ui:rounded-lg ui:bg-slate-50 ui:p-3 ui:font-sans ui:text-sm ui:text-slate-700">{!! $h !!}</pre>
            @endforeach
          </div>
        </x-ui.card>
      @endforeach

    @else

      <x-ui.card flush>
        @if($frameworks->isEmpty())
          <x-ui.empty icon="books">{{ __('None.') }}</x-ui.empty>
        @else
          <x-ui.table>
            <thead>
              <tr>
                <th>{{ __('Provider') }}</th>
                <th>{{ __('Framework') }}</th>
                <th>{{ __('Version') }}</th>
                <th>{{ __('Language') }}</th>
                <th></th>
              </tr>
            </thead>
            {{-- One tbody per framework: its row + its content, toggled by the caret --}}
            @foreach($frameworks as $framework)
              <tbody x-data="{ isExpanded: false }">
                <tr>
                  <td>
                    <x-ui.badge level="info">{{ \Illuminate\Support\Str::lower($framework->provider) }}</x-ui.badge>
                  </td>
                  <td>
                    <div class="ui:font-semibold">{{ \Illuminate\Support\Str::upper($framework->name) }}</div>
                    <div class="ui:text-slate-500">{{ $framework->description }}</div>
                  </td>
                  <td>{{ $framework->version }}</td>
                  <td>
                    <x-ui.tag>{{ $framework->locale }}</x-ui.tag>
                  </td>
                  <td>
                    <div class="ui:flex ui:items-center ui:justify-end ui:gap-2">
                      @if($framework->loaded())
                        <x-ui.icon-button icon="trash" :title="__('Unload')" onclick="unload({{ $framework->id }}, event)"
                                          class="ui:text-red-600 ui:hover:text-red-700"/>
                      @else
                        <x-ui.icon-button icon="download-simple" :title="__('Load')" onclick="load({{ $framework->id }}, event)"
                                          class="ui:text-emerald-600 ui:hover:text-emerald-700"/>
                      @endif
                      <x-ui.icon-button icon="caret-right" :title="__('Details')" x-on:click="isExpanded = !isExpanded"
                                        x-bind:aria-expanded="isExpanded"
                                        x-bind:class="isExpanded ? 'ui:rotate-90' : ''"
                                        class="ui:transition-transform"/>
                    </div>
                  </td>
                </tr>
                <tr x-show="isExpanded" x-cloak>
                  <td colspan="5" class="ui:bg-slate-50 ui:text-slate-700">
                    {!! $framework->html() !!}
                  </td>
                </tr>
              </tbody>
            @endforeach
          </x-ui.table>
        @endif
      </x-ui.card>

    @endif
  </div>
  <script>

    const load = (id, event) => {
      event.preventDefault();
      event.stopPropagation();
      loadFrameworkApiCall(id, response => window.toaster.toastSuccess(response.msg));
    };

    const unload = (id, event) => {
      event.preventDefault();
      event.stopPropagation();
      unloadFrameworkApiCall(id, response => window.toaster.toastSuccess(response.msg));
    };

  </script>
</x-layouts.app>
